코멘트와 코드가 다른 부분 수정
kkamagui/mint64os pull request #2
Opened 2021-01-03 11:02 UTC by EugeneChung

2021-01-16 13:17 UTC, kkamagui requested changes
안녕하세요, @EugeneChung 님.
좋은 의견을 주셔서 감사합니다. ^^

사실 0x7C00을 0x07C0으로 수정 의견 주신 부분은 0x7C00이 의미상 맞는 것 같습니다.
0x7C00이 부트로더의 시작 주소인데, 이 값을 세그먼트 레지스터의 값으로 바꾸기 때문에 실제 값은 0x07C0이 된다는 의미의 주석이거든요.

만약 해당 부분을 수정한다면 "시작 어드레스(0x7C00)을 세그먼트 레지스터 값(0x07C0)으로 변환" 이라고 쓰는 것이 더 정확할 것 같습니다.
그리고 비디오 메모리 어드레스 부분 또한 동일한 방법으로 수정되어야 할 것 같습니다.

혹시 이 부분을 수정해서 다시 pull-request를 보내주실 수 있을까요?

감사합니다.

2021-01-16 14:15 UTC, EugeneChung commented
책 4.3.4 세그먼트 레지스터 초기화 부분에 `부트 로더의 시작 어드레스(0x7C00)를 세그먼트 레지스터 값으로 변환' 이라고 주석이 있었네요.

책 잘 보고 있습니다. ^^

2021-01-16 14:25 UTC, kkamagui requested changes

2021-01-16 14:25 UTC, kkamagui commented on 00.BootLoader/BootLoader.asm
> +    mov ax, 0xB800  ; 비디오 메모리의 시작 어드레스(0xB800)를 세그먼트 레지스터 값(0xB800)으로 변환
안녕하세요, @EugeneChung 님.

수정해서 pull-request를 다시 보내주셔서 너무 감사합니다.

확인해보니 보내주신 부분에 오타가 있는 것 같은데요,
"시작 어드레스(0xB800)를 세그먼트 레지스터 값(0x0B80)으로"로 수정해주실 수 있을까요?

감사합니다.

2021-01-16 14:38 UTC, EugeneChung commented on 00.BootLoader/BootLoader.asm
> +    mov ax, 0xB800  ; 비디오 메모리의 시작 어드레스(0xB800)를 세그먼트 레지스터 값(0xB800)으로 변환
비디오 메모리의 기준  물리 어드레스가 0xB8000 이니까, "시작 어드레스(0xB8000)를 세그먼트 레지스터 값(0xB800)으로"이 아닐까요?

2021-01-16 16:58 UTC, kkamagui commented on 00.BootLoader/BootLoader.asm
> +    mov ax, 0xB800  ; 비디오 메모리의 시작 어드레스(0xB800)를 세그먼트 레지스터 값(0xB800)으로 변환
앗 죄송합니다. 제가 말씀을 잘 드렸네요.
시작 어드레스(0xB8000)를 세그먼트 레지스터 값(0xB800)으로" 로 수정해 주십사 말씀을 드렸어야 했는데...
말씀 감사합니다.

2021-01-17 01:04 UTC, EugeneChung commented on 00.BootLoader/BootLoader.asm
> +    mov ax, 0xB800  ; 비디오 메모리의 시작 어드레스(0xB800)를 세그먼트 레지스터 값(0xB800)으로 변환
덕분에 저도 공부가 많이 됐습니다.

2021-01-17 13:58 UTC, kkamagui commented
@EugeneChung 님 감사합니다.
수동으로 merge를 해드렸습니다. 결과는 아래에서 확인하실 수 있습니다.
https://github.com/kkamagui/mint64os/commits/master

완독하시길 기원합니다. ^^

2021-01-17 13:58 UTC, closed without merging